[package]
name = "opencv-test"
version = "0.1.0"
authors = ["Renato Moitinho <renato.dias@b2wdigital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.29.2"
regex = "1.3.4"
